### ISSUE TITLE
How to finish or pop fragment?

### ISSUE THREAD

**Issue by matghazaryan** [hamedsilver/ArchApp#1]
In the example I can see you have Navigation To and Back. 

When I am calling To is there a way to finish or pop last fragment ?

A->B -pop A and in B press back close the app.

I tried to set app:popUpToInclusive="true" in xml but it not worked.

Is there other way to do it with programmatically?

**Comment by hamedsilver** [comment]
You can add an optional navOptions property to your To and Back method and pass your nav options

**Comment by hamedsilver** [comment]
`sealed class NavigationCommand {
 data class To(val directions: NavDirections, val options: NavOptions? = null, val closeKeyboard: Boolean = true) : NavigationCommand() object Back: NavigationCommand() data class PopBackStackTo(@IdRes val destinationId :Int ,val inclusive :Boolean ): NavigationCommand() data class ToPin(val id: String, val info: Bundle? = null, val args: NavArgs? = null) : NavigationCommand() object Forbidden : NavigationCommand()
 }  `

**Comment by matghazaryan** [comment]
What to add on observeNavigation and on BaseViewmodel class ?

**Comment by hamedsilver** [comment]
`when (command) { is NavigationCommand.To -> { if (command.closeKeyboard) view?.closeSoftKeyboard() findNavController().navigate(command.directions, command.options) } is NavigationCommand.Back -> { view?.closeSoftKeyboard() findNavController().navigateUp() } is NavigationCommand.PopBackStackTo -> { view?.closeSoftKeyboard() findNavController().popBackStack(command.destinationId , command.inclusive) } `

**Comment by hamedsilver** [comment]
`fun navigate(directions: NavDirections, options: NavOptions? = null) { _navigation.value = Event(NavigationCommand.To(directions, options)) } fun popBackStackTo(@IdRes destinationId :Int, inclusive :Boolean){ _navigation.value = Event(NavigationCommand.PopBackStackTo(destinationId, inclusive)) } fun navigateBack() { _navigation.value = Event(NavigationCommand.Back) } `

**Comment by matghazaryan** [comment]
Thank you very much but there is other problem

if (it.status == Resource.Status.SUCCESS) {
                    navigate(SplashFragmentDirections.actionSplashFragmentToLoginFragment())
                    popBackStackTo(R.id.loginFragment,true)
                }


navigate not working when there is popBackStackTo, when I am removing it navigate working good.

**Comment by hamedsilver** [comment]
Dont use navigate to and back at the same time ,
`navigate(FragmentCreditScoringResultDirections.actionCreditScoringResultToOtpFail(), NavOptions.Builder().setPopUpTo(R.id.fragment_credit_scoring_result, true).build()) `

**Comment by hamedsilver** [comment]
For back senario u can back to direction by popbackStackTo

**Comment by matghazaryan** [comment]
Thank you Hamed for your help

 ```
navigate(SplashFragmentDirections.actionSplashFragmentToLoginFragment(),NavOptions.Builder().setPopUpTo(
                        R.id.loginFragment,true).build())
```

the result is the same it's not clearing previous fragment ((

**Comment by hamedsilver** [comment]
Whats your flow
What frgments in your navigation stack?

**Comment by matghazaryan** [comment]
Here is the example
https://github.com/matghazaryan/MVVM-DemoApp-Android/tree/develop

Can you help me find what's wrong here ?

**Comment by matghazaryan** [comment]
It's the pretty the same example as yours.

**Comment by hamedsilver** [comment]
Just setPopUpTo splash and set inclusive true
